### ISSUE TITLE
error on Emacs 28.1

### ISSUE THREAD

**Issue by maxxcan** [xl666/enime#1]
The error when load the .el file is:

Debugger entered--Lisp error: (void-function s-trim)

**Comment by xl666** [comment]
It seems you haven't installed one of the dependencies: https://github.com/magnars/s.el

**Comment by maxxcan** [comment]
I already have it installed. 
![image](https://user-images.githubusercontent.com/4959947/164088323-4185cbbd-679e-4011-835a-0760d5eba86b.png)

**Comment by xl666** [comment]
Ok, I missed the explicit require for s.el, it should be fixed in last commit, thanks for reporting

**Comment by maxxcan** [comment]
thanks to you. I only want to say you that I like so much your package and I use a lot.
